### ISSUE TITLE
persistence not starting/working

### ISSUE THREAD

**Issue by ITShibaInu** [moscajs/aedes-persistence-mongodb#12]
Hi im new to aedes. I am trying to use aedes-persistence-mongodb for persistence but dont know how to start. Here is my code:

`let aedesPersistenceDB = require('aedes-persistence-mongodb')
let persistence = aedesPersistenceDB({
    url: "mongodb://localhost:27017/persistence"
})
let aedesOpt = {
    concurrency: config.aedesOpt.concurrency,
    heartbeatInterval: config.aedesOpt.heartbeatInterval,
    connectTimeout: config.aedesOpt.connectTimeout,
    persistence: persistence
}
let aedes = require('aedes')(config.aedesOpt)
let server = require('net').createServer(aedes.handle)
let port = 1883

server.listen(port, function () {
    logger.debug('server listening on port', port)
})`

And i try to use the api in this way:
`aedesPersistenceDB.subscriptionsByTopic = (pattern, callback) => {
    console.log('call this when a PUBLISH with qos: 1 or qos: 2 is received.')
}`

I have a client with clean : false subscribe to topic/sth. The client goes offline and i publish a message to topic/sth. However i cannot find anything on the database (i expected it likes how mosca works, correct me if im wrong). I can get the message when the client is online on same server. But if it switches server(even with same persistence) i cannot get message back.

My question is:
1. Is there a way to check if persistence is ready? (event or callbacks) If any, how to implement it? (some sample code would be great)
2. Im not sure if i use the apis in correct way. Would be appreciated if you can show me some samples of using them.
3. In mosca, client can retrieve persistent session even when switching server if servers are connected to the same persistence. Can aedes-persistence-mongodb also achieve this?

**Comment by mcollina** [comment]
Why you are overriding `subscriptionsByTopic`? That is not clear to me.

You need to also use mqemitter-mongodb (or mqemitter-redis).

**Comment by ITShibaInu** [comment]
Sorry i don't know how to use it lol

Does it mean that i will need to use mqemitter-mongodb if i want to use persistence?

**Comment by mcollina** [comment]
You will see messages in the persistence if you connect with clean: false and subscribe with qos >= 1. Plus, you will need to connect with same clientId.

the mqemitter is needed to share message delivery between processes.

**Comment by ITShibaInu** [comment]
I have tried the following:

connect the client with clean: false
client subscribes a topic with qos = 1
connect with same clientid everytime

here is the code:

```
   let mqtt = require('mqtt')

   let client = mqtt.connect(config.mqttconnection.connectionString, {
        will : {
            topic: `${config.mqttDeviceId}/info/status`,
            payload : 'ERROR',
            qos : 2
        },
        clientId : config.mqttDeviceId,
        clean : false
    });

    client.on('connect', function () {
        client.publish(`${config.mqttDeviceId}/info/status`, 'ONLINE');
        console.log(`+-----------------------------------+`);        
        console.log(`| client [${config.mqttDeviceId}] goes online |`);
        console.log(`+-----------------------------------+`);
        client.subscribe(`event/+/+/+`, { qos : 1 });
    })
    client.on('message', function (topic, message) { 
        // message is Buffer
        console.log(topic.toString() + " : " + message.toString());
    })
```

I was able to receive messages that were published while the client is offline after getting back online. However i didn't see the messages in the database. What i want to achieve is clients can get back the messages even they are connected to different aedes servers which are connected to same database (clustering, don't know if it is the right term). Am i missing anything in the above code?

**Comment by mcollina** [comment]
I am a bit lost. Is it working as expected or not?
In which collections are you checking for messages in the DB?

**Comment by ITShibaInu** [comment]
Not as expected.

What i expected is like the persistence in Mosca, where the message can be found in the persistence database. so that i can get back the message even the client is connecting to different server, as long as the server is connected to the same persistence database.

I am expecting the collections like "packets", "subscriptions" will be created automatically in the database (like Mosca).

**Comment by mcollina** [comment]
So, can you upload a full example with two clients and a cluster of aedes instance, with instructions on how to run it?

> I was able to receive messages that were published while the client is offline after getting back online.

This sentence seem to indicate that the system is working correctly. Or I am misunderstanding something?

> I am expecting the collections like "packets", "subscriptions" will be created automatically in the database (like Mosca).

Those collections are internal and __should not be used__.

**Comment by ITShibaInu** [comment]
I uploaded the code here:
[https://github.com/ITShibaInu/demo](url)

1. Run `npm install` in the root folder
2. There are 2 servers in aedes-server folder and 2 clients in mqtt-client folder. Start up by running following in corresponding folders:
`node aedes-server-alpha.js`
`node aedes-server-beta.js`
`node client.js`
`node aedes-client.js`
3. Now client [admin] and client [aedes-client] should connect to aedes-server-alpha
4. The clients use http requests to simulate publishing to topics. Send get request `http://localhost:3003/?connect=false` to disconnect client from server (connect=true to connect). Send get request `http://localhost:3003/?topic=event/put/sth/here&payload={"msg":"message"}` to publish. Client [admin] is subscribing event/+/+/+ so it will receive the message.
5. Stop client [admin], publish message with client [aedes-client] and then start client [admin] again. Client [admin] can get back the subscribed messages.
6. Stop client [admin], change `mqtt://localhost:8883` to `mqtt://localhost:8884` in client.js (connect client [admin] to aedes-server-beta), publish message with client [aedes-client] and then start client [admin] again. This time client [admin] cannot get back the messages. 
7. Stop client [admin], change `mqtt://localhost:8883` to `mqtt://localhost:8884` in client.js (connect client [admin] to aedes-server-beta), start client [admin] again and then publish message with client [aedes-client]. Client [admin] cannot receive message as well.

Since I use same persistence in both servers, I expect that even if I change the connected server from alpha to beta, the client can get back the messages.

**Comment by mcollina** [comment]
Can you try subscribing from the client, instead of calling `client.subscribe()`?

**Comment by ITShibaInu** [comment]
How to subscribe from client instead of calling `client.subscribe()`? I am following https://www.npmjs.com/package/mqtt for subscribing. Maybe I am too new to this so any example or code pieces would be great help to me...

**Comment by mcollina** [comment]
I mean https://github.com/mqttjs/MQTT.js#subscribe.

Unfortunately I won't have time for the coming while to debug this. If someone else wants to pick it up, please do so.

**Comment by ITShibaInu** [comment]
Oh... i used to think `client.subscribe()` is `mqtt.Client#subscribe`. I have no idea how to use this one. I tried to use `mqtt.Client#subscribe` directly and the syntax is not correct.
