### ISSUE TITLE
[bug] Index for packet TTL uses key `added` but the key in documents is `packet.added`

### ISSUE THREAD

**Issue by schwing** [moscajs/aedes-persistence-mongodb#50]
**System Information**
- Aedes: 0.42.5
- NodeJS: 12.18.3
- OS: Alpine Linux
- Arch: x86_64

**Describe the bug**
For all packet collections except `retained`, the index for packet TTL is configured for the key `added` but this module sets the key `packet.added` in documents. This causes packet documents to have no TTL.

In our case, MongoDB eventually becomes overloaded querying through stale messages in the `outgoing` collection, resulting in cursor timeouts and messages not being delivered.

Index created for the `outgoing` collection by this module:
```
[
    2,
    {
        "added" : 1
    },
    "ttl",
    "mqttbroker.outgoing",
    10
]
```

Example packet document (some irrelevant information redacted):
```
{
    "_id" : ObjectId("<ObjectId>"),
    "clientId" : "<clientId>",
    "packet" : {
        "cmd" : "publish",
        "brokerId" : "46115500",
        "brokerCounter" : 9205,
        "topic" : "<topic>",
        "payload" : { "$binary" : "<payload>", "$type" : "00" },
        "qos" : 1,
        "retain" : false,
        "dup" : false,
        "messageId" : null,
        "added" : ISODate("2020-08-14T23:34:40.033Z")
    }
}
```

This affects all packet collections that indexes are created for except `retained` because of differences in how retained packets are stored. https://github.com/moscajs/aedes-persistence-mongodb/blob/6ca1ffa3b1958981ec8edd7e00a7d3b01f9d5889/persistence.js#L101-L117

**To Reproduce**
1. Configure packet TTLs on Aedes init. 
2. Create a QoS 1 subscription to a topic.
3. Publish to the topic.
4. Verify that the packet document in the `outgoing` collection is retained indefinitely beyond the configured packet TTL.

**Expected behavior**
Packet documents expiring based on the configured TTL.

**Additional context**
Before creating a PR, I'd like to understand the intention and what I should change. Is there a purpose for the difference in schema between `will`/`outgoing`/`incoming` and `retained`, or should all of these have similar schema?

Should the schema be?
a. What I pasted above, which is how documents look in collections `will`/`outgoing`/`incoming` currently.
b. The schema of `retained` documents which looks like the others but flattened:
```
{
    "_id" : ObjectId("<ObjectId>"),
    "topic" : "<topic>",
    "added" : ISODate("2020-08-17T16:55:57.896Z"),
    "brokerCounter" : 140,
    "brokerId" : "52b7596d",
    "cmd" : "publish",
    "dup" : false,
    "messageId" : null,
    "payload" : { "$binary" : "<payload>", "$type" : "00" },
    "qos" : 1,
    "retain" : true
}
```
c. Only update the indexes for `will`/`outgoing`/`incoming` TTLs to use `packet.added` and leave everything else as-is.

Given what the indexes are, it looks like b. was the intention.

Happy to create a PR with a fix once I understand which route to take.

**Comment by schwing** [comment]
Thinking over it again, option c. also makes sense because packets belong to a clientId in `will`/`outgoing`/`incoming`, but not in `retained`.

**Comment by robertsLando** [comment]
Nice catch @schwing . If you submit a PR I will happy to review it
