### ISSUE TITLE
[feat] Mongo query performance

### ISSUE THREAD

**Issue by scagood** [moscajs/aedes-persistence-mongodb#64]
I suggest we add the following indexes to generally improve performance (My mongo instances report using this index in the region of 3k times per second :sweat_smile:)

```js
db.outgoing.createIndex({ clientId: 1, 'packet.brokerId': 1, 'packet.brokerCounter': 1 });
db.outgoing.createIndex({ clientId: 1, 'packet.messageId': 1 });
db.inbound.createIndex({ clientId: 1, 'packet.brokerId': 1, 'packet.brokerCounter': 1 });
db.inbound.createIndex({ clientId: 1, 'packet.messageId': 1 });
```

I assume a similar set of indexes should be added to the other collections but I am yet to use them heavily.

**Comment by scagood** [comment]
I am happy to PR if you agree this is worth while :grin:

**Comment by mcollina** [comment]
Send the PR! This is highly welcomed!
