### ISSUE TITLE
[question] Regarding subscription TTL behavior

### ISSUE THREAD

**Issue by simonnilsson** [moscajs/aedes-persistence-mongodb#78]
If I understand the current implementation correctly it works like this: when you set the `ttl.subscriptions` that subscription will be persisted for the specified duration **since the subscription was set up**.

Would it not make a lot more sense for this ttl to be based on when the client was **last connected to the broker**?

Example use case with `ttl.subscriptions = 3600 * 24` (24h):

> Client connects and sets up a subscription, after 23h the client loses the connection to broker. 2h later (25h passed since subscription) client connects again but subscription is gone and 1h of messages have been lost.

So my suggestion is basically that the ttl of subscription would be pushed forward in time as long as the client is connected and not start "ticking" until the client disconnects. This functionality could be enabled with an option flag to keep backward combability.

Or is the idea that the client should regularly refresh the subscription to keep it active?

If this is a feature that seems reasonable, I would be willing to put some work into implementing it and making a pull-request.

**Comment by simonnilsson** [comment]
> Or is the idea that the client should regularly refresh the subscription to keep it active?

This solution does not seem to work either as the `added` field in mongodb does not update when subscribing to the same topic again.

**Comment by robertsLando** [comment]
In the particular case of subscriptions it would make sense, a workaround to this would be to periodically restart mqtt connection on client side

**Comment by simonnilsson** [comment]
That is a workaround yes, in my case I'm not always in control of the client side. And requiring a third-party to regularly reconnect does not seem like the best solution.

**Comment by robertsLando** [comment]
I dunno how you could implement such feature in persistence as you don't have any event trigger to know when a client goes offline

**Comment by robertsLando** [comment]
By looking at [redis implementation](https://github.com/moscajs/aedes-persistence-redis/blob/master/persistence.js) seems subscriptions doesn't have a ttl at all

**Comment by simonnilsson** [comment]
I haven't gone so far as to look into how to solve it, it is possible that it can't be done without changes to Aedes itself. And yes I also noticed that Redis does not have a ttl for subscriptions.

**Comment by robertsLando** [comment]
The solution proposed [here](https://github.com/moscajs/aedes-persistence-mongodb/issues/78#issuecomment-1240681363O should work well if you want to submit a PR
